### ISSUE TITLE
Yo Luke Bouch!

### ISSUE THREAD

**Issue by JacobBennett** [lukebouch/lukebouch-micro-blog#1]
# Hey Luke 👋

This was the only way I could find to get a hold of you.

I found you on

- LinkedIn
- Laracasts
- lukebouch.com
- Luke Bouch Micro blog
- Some website about Racing Drones (maybe?)

but no luck finding an email address to reach you at!

In any case, hoping to chat with you about a possibility to maybe work together? If you have an interest, you can message me on Twitter, if you happen to have that at (http://twitter.com/jacobbennett).

Or if email is more your style, here is a temp email address I can expose to the world without getting spammed to death :) 

slugger-parades0i@icloud.com

Hit me up!

**Comment by lukebouch** [comment]
Hey @JacobBennett!

I don't know how I missed this issue. It was great talking to you on the phone. I'm very exiting!
